version: '3.8'

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:25.9
    restart: always
    command: /bin/bash -c "tar -xvzf /tmp/bundle.tar.gz -C / && /entrypoint.sh"
    ports: 
      - '127.0.0.1:9000:9000'
      - '127.0.0.1:8123:8123'
    volumes:
      - ./tmp/clickhouse-server-custom-config.xml:/etc/clickhouse-server/config.d/clickhouse-server-custom-config.xml:ro
      - ${BUNDLE_PATH:-./tmp/bundle.tar.gz}:/tmp/bundle.tar.gz:ro
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
      - LOG_LEVEL=${LOG_LEVEL}

  minio:
    image: minio/minio:latest
    restart: always
    command: ['server', '/data', '--address', ':9001', '--console-address', ':9002']    
    ports:
      - '9001:9001'
      - '9002:9002' 
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123

  minio-bootstrap:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set local http://minio:9001 minio minio123;
      /usr/bin/mc mb local/test01;
      exit 0;
      "
