with
    sample as (
        select * from values(
            'type String, data String',
            ('TransactionEnvelope', 'AAAAAgAAAAC634lTxnGbYc1KpIJ5cKQPEHU3t2Jyemrv9T7cMxIcVwAAYhUC3\/xzAAHHtAAAAAIAAAABAAAAAAAAAAAAAAAAaMgVhwAAAAEAAAAAA4NeEgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAFUAAAAAAAAAQAAAAEAAAAAiEnJHsmNsUt\/xQoKKEJMhOQu6+bS5Nc831QU9agQ8Y4AAAANAAAAAXlYTE0AAAAAIjbXcP4NPgFSGXXVz3rEhCtwldaxqddo0+mmMumZBr4AAAAAA6kIDQAAAACISckeyY2xS3\/FCgooQkyE5C7r5tLk1zzfVBT1qBDxjgAAAAJIRUxJWAAAAAAAAAAAAAAAygdj6ZzTifcr\/tqc4WolrzH5q5FGdOOgT4g76B0MnqQAAAAAA6kIDQAAAAQAAAABVVNEQwAAAAA7mRE4Dv6Yi6CokA6xz+RPNm99vpRr7QdyQPf2JN8VxQAAAAFVU0RaAAAAABU1vFzNd\/lISJw6iXQQ5Z5eCLyuUwe8EXSNdmHAmXtPAAAAAVhSUAAAAAAAbxevnWvOKrClBjNaVKWqpIzv2s3K\/6NEm2G4Kywq3xEAAAAAAAAAAAAAAAIzEhxXAAAAQIqEgzRVC6HuY0UAeWsxLZ4pS\/0SPk9UL177QU0zpVuKRhPaUs8uIqtXqdWAz\/MSIC1X0l6XS29rwmaruoKfPwyoEPGOAAAAQFmL95GqmaZMLuncvR41d5zzGB3ANGntGXzCNv9DN8nQLu+God7kgGdTdgXNhx8JFWxbxwijWZ4rjibw4G32Ggc='),
            ('TransactionEvent', 'AAAAAAAAAAAAAAABJbT82FmuwvpjSEOMSJs8PBDJi20hvk\/TyzDLaJU++XcAAAABAAAAAAAAAAIAAAAPAAAAA2ZlZQAAAAASAAAAAAAAAABmOMzcP3GB7aqvq\/w2S20taRvi4ycXhF9ChvSvlfhGjAAAAAoAAAAAAAAAAAAAAAAAAAEs')
        )
    )

select stellar_xdr_decode(type, data) as decoded from sample

settings output_format_arrow_string_as_string=0
